#!/usr/bin/env node
// Copies skills/, templates/, process/ from the framework repo root into cli/,
// so they ship inside the published package. npm can only package files that
// live inside the package root (cli/) -- it cannot reach sibling directories
// like ../skills/. These vendored copies are build artifacts (gitignored,
// regenerated by this script), never hand-edited -- the real source stays at
// the framework repo root, same rule as .claude/.agents/.cursor (see AGENTS.md
// "Source vs. installed artifacts").

const fs = require('fs');
const path = require('path');

const frameworkRoot = path.resolve(__dirname, '..', '..');
const cliRoot = path.resolve(__dirname, '..');
const FOLDERS = ['skills', 'templates', 'process'];

function copyRecursiveSync(src, dest) {
  const stats = fs.statSync(src);
  if (stats.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const child of fs.readdirSync(src)) {
      copyRecursiveSync(path.join(src, child), path.join(dest, child));
    }
  } else {
    fs.copyFileSync(src, dest);
  }
}

for (const folder of FOLDERS) {
  const src = path.join(frameworkRoot, folder);
  const dest = path.join(cliRoot, folder);

  if (!fs.existsSync(src)) {
    console.error(`vendor.js: source folder missing: ${src}`);
    process.exit(1);
  }

  fs.rmSync(dest, { recursive: true, force: true });
  copyRecursiveSync(src, dest);
  console.log(`Vendored ${folder}/ into cli/${folder}/`);
}
